### ISSUE TITLE
邮件发送服务的调试

### ISSUE THREAD

**Issue by FrankyYang** [limingth/maodou#15]
server/method.js 中 sendEmail方法，调试一下使之能够正常发邮件。可参考：https://github.com/limingth/hands-on-meteor/， sendEmail的API不要动。

**Comment by limingth** [comment]
@Ken-Liu  之前的 mailgun 账号帮忙看看是不是过期了，如果是，贾天可以 重新申请以下。

**Comment by Ken-Liu** [comment]
的确是账户被禁用了。需要到mailgun上重新注册一个新账户。如果账户刚注册是disable的。按提示给技术支持发说明邮件即可。几小时内就可用了。

**Comment by Ken-Liu** [comment]
禁用原因是未明确说明账号的应用用途及邮件内容等，防止用来发送垃圾邮件

**Comment by limingth** [comment]
@klbjlabs  参考 http://blog.ploki.info/send-email-with-meteor-mailgun/  申请的时候注意 @Ken-Liu 的提醒

**Comment by klbjlabs** [comment]
mailgun的管理员已经激活了我的账号功能，发了几封邮件试了一下 可以用。我修改了 `server/seed.js` 文件的第二行，没改错吧。。。

**Comment by limingth** [comment]
没问题，测试通过！
